spring:
  application:
    name: havebeen
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/havebeen
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:topsecret}
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=200,expireAfterWrite=60m